import duckdb
c=duckdb.connect('/Users/mariaaleu/workspace/Polymarket_Weather_Agent/data/pmw.duckdb',read_only=True)
c.execute("create temp table ev as select * from read_csv_auto('/Users/mariaaleu/.claude/jobs/43deec01/tmp/disc60/ev.csv', all_varchar=true)")
c.execute("""create temp table pm as select m.event_id, p.market_id, min(p.fetched_at) f from price_history p join markets m using(market_id) group by all""")
print("-- 09-07 21:00..09-08 01:00 run: by station")
print(c.sql("""select ev.st, count(distinct pm.event_id) evs, count(*) mk, count(distinct ev.d) dates from pm join ev using(event_id)
  where pm.f between '2026-09-07 20:00:00+02' and '2026-09-08 01:00:00+02' group by 1 order by 3 desc"""))
print(c.sql("""select count(*) mk, count(distinct pm.event_id) evs, count(distinct ev.d) dates, min(pm.f), max(pm.f) from pm join ev using(event_id) where pm.f between '2026-09-07 20:00:00+02' and '2026-09-08 01:00:00+02'"""))
print("-- markets per date in that run")
print(c.sql("""select k, count(*) dates from (select ev.d, count(*) k from pm join ev using(event_id) where pm.f between '2026-09-07 20:00:00+02' and '2026-09-08 01:00:00+02' group by 1) group by 1"""))
print("-- 09-09 complete-events run")
print(c.sql("""select count(*) mk, count(distinct event_id) evs, min(event_id) e0, max(event_id) e1, min(f), max(f) from pm where f >= '2026-09-09 15:00:00+02'"""))
print(c.sql("""select count(distinct event_id) from pm where f >= '2026-09-09 15:00:00+02' """))
print("-- forecasts coverage")
print(c.sql("""select dataset_version, min(target_date), max(target_date), count(distinct station||cast(target_date as varchar)) pairs from weather_forecasts group by 1"""))
print(c.sql("""select station, cast(target_date as date) d from weather_forecasts where station='EGLC' and cast(target_date as date) in ('2026-04-02','2026-04-08','2026-03-09','2026-07-14') group by all"""))
print("-- events with forecast pair, not complete, event_id string < max complete-run event id")
print(c.sql("""with cr as (select max(event_id) mx from pm where f >= '2026-09-09 15:00:00+02')
  select (ev.event_id <= (select mx from cr)) below_cap, (n_store=n_cat) complete, count(*) from ev
  where exists(select 1 from weather_forecasts w where w.station=ev.st and cast(w.target_date as date)=cast(ev.d as date) and w.dataset_version='backfill_2b_v1')
  group by all order by 1,2"""))
print(c.sql("""with cr as (select max(event_id) mx from pm where f >= '2026-09-09 15:00:00+02')
  select ev.* from ev where n_store<n_cat and event_id <= (select mx from cr) and exists(select 1 from weather_forecasts w where w.station=ev.st and cast(w.target_date as date)=cast(ev.d as date) and w.dataset_version='backfill_2b_v1') limit 20"""))
print("-- EGLC truncated events: which run first fetched them")
print(c.sql("""select ev.n_store, case when min(pm.f) < '2026-09-07' then 'r1_0906' when min(pm.f)<'2026-09-08 12:00:00+02' then 'r2_0907' when min(pm.f)<'2026-09-09 12:00:00+02' then 'r3_0908' else 'r4_0909' end run, count(distinct ev.event_id)
  from ev join pm using(event_id) where ev.st='EGLC' group by ev.event_id, ev.n_store""").aggregate("n_store, run, count(*) events").order("run, n_store"))
